In [2]:
import pandas as pd

In [5]:
pd.Series([40000,65000,60000],index=["A","B","C"])
pd.Series({"A":40000,"B":65000,"C":60000})

A    40000
B    65000
C    60000
dtype: int64

In [6]:
pd.DataFrame({
    "name": ["Aman", "Riya"],
    "salary": [40000, 65000]
})

   name  salary
0  Aman   40000
1  Riya   65000

In [7]:
pd.DataFrame([
    {"name": "Aman", "salary": 40000},
    {"name": "Riya", "salary": 65000}
])

   name  salary
0  Aman   40000
1  Riya   65000

In [9]:
df=pd.read_csv("employees_100.csv")
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [11]:
df.head()
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [12]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
65,168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01

In [16]:
df.shape
df.dtypes
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [18]:
df.columns

Index(['employee_id', 'name', 'department', 'city', 'age', 'salary',
       'experience', 'performance_score', 'projects_completed',
       'joining_date'],
      dtype='object')

In [19]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [20]:
df["salary"]

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: object

In [21]:
df[["name","salary"]]

              name salary
0     Swati Kapoor  70719
1   Kavya Malhotra  77058
2     Manish Desai  69911
3         Neha Das  69993
4        Isha Nair  88216
..             ...    ...
95     Nikhil Nair  55740
96      Neha Desai  52250
97      Neha Reddy    NaN
98     Priya Nayak  56821
99     Kavya Joshi  69499

[100 rows x 2 columns]

In [27]:
df.set_index("employee_id")

KeyError: "None of ['employee_id'] are in the columns"

In [28]:
df

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [32]:
df.loc[184:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [34]:
df.iloc[0:10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [36]:
df.loc[154:145][["name","city","age"]]

                       name       city   age
employee_id
154          Kavya Malhotra     Mumbai   NaN
171            Manish Desai  Hyderabad  23.0
146                Neha Das       Pune  28.0
145               Isha Nair        NaN  32.0

In [37]:
df[df["age"]>40]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [39]:
df.columns

Index(['name', 'department', 'city', 'age', 'salary', 'experience',
       'performance_score', 'projects_completed', 'joining_date'],
      dtype='object')

In [41]:
df[(df["department"]=="Finance")&(df["age"]>30)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18

In [44]:
df[df["department"].isin(["Engineering","Data Science"])]
df[df["experience"].between(2,5)]
df[df["name"].str.contains("Verma")]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10

In [46]:
df[["salary"]]

            salary
employee_id
184          70719
154          77058
171          69911
146          69993
145          88216
...            ...
161          55740
172          52250
115            NaN
193          56821
152          69499

[100 rows x 1 columns]

In [47]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [49]:
df2=df.dropna()

In [50]:
df2.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [51]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [52]:
df.dropna(subset=["city"])

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [53]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [61]:
df["age"]=df["age"].fillna(df["age"].mean())

In [56]:
df["salary"]=df["salary"].str.replace(",","",regex=False)
df["salary"]=pd.to_numeric(df["salary"],errors="coerce")
df["salary"]=df["salary"].fillna(df["salary"].median())

In [ ]:
df["salary"].dtype

dtype('float64')

In [62]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [63]:
df["department"].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [67]:
df["department"]=df["department"].fillna(df["department"].mode()[0])

In [68]:
df["city"]=df["city"].fillna(df["city"].mode()[0])

In [69]:
df.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [71]:
df=df.reset_index()

In [73]:
df.duplicated().sum()

0

In [74]:
df.duplicated(subset=["employee_id"]).sum()

4

In [76]:
df.drop_duplicates(subset=["employee_id"],keep="first")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.000000,55740.0,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.000000,52250.0,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06
98,193,Priya Nayak,HR,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25

In [77]:
df["joining_date"]=pd.to_datetime(df["joining_date"])

In [78]:
df["joining_date"].dtype

dtype('<M8[ns]')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          100 non-null    object
 3   city                100 non-null    object
 4   age                 100 non-null    float64
 5   salary              100 non-null    float64
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 7.9+ KB

In [80]:
df["annual_salary"]=df["salary"]*12

In [81]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0

In [82]:
def categorize(num):
    if num>5:
        return "Experienced candidate"
    elif num <= 5:
        return "Learner"

In [83]:
df["experience_status"]=df["experience"].apply(categorize)

In [84]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate

In [ ]:
#department_codes={"Engineering":"ENG","Marketing":"MKT","Finance":"FIN"}
#df["department_codes"]=df["department"].map(department_codes)

In [87]:
df_salary_sorted=df.sort_values(by="employee_id")

In [88]:
df["department"].unique()

array(['Data Science', 'engineering', 'Engineering', 'Sales', 'HR',
       'Marketing', ' Marketing ', 'Finance', ' Finance ', ' HR ',
       'FINANCE', 'SALES', 'MARKETING'], dtype=object)

In [89]:
df["department"]=df["department"].str.strip().str.title()

In [90]:
df["department"].unique()

array(['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing',
       'Finance'], dtype=object)

In [92]:
df.sort_values(
    by=["department", "salary"],
    ascending=[True, False]
)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate
59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22,941580.0,Learner
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,917100.0,Learner
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267.0,5,6,3,2023-01-24,915204.0,Learner
...,...,...,...,...,...,...,...,...,...,...,...,...
48,163,Rahul Chatterjee,Sales,Kolkata,25.0,60015.0,0,8,9,2023-05-10,720180.0,Learner
17,178,Vikram Kapoor,Sales,Chennai,29.0,57858.0,3,7,1,2020-06-26,694296.0,Learner
44,128,Rohan Chatterjee,Sales,Mumbai,26.0,52862.0,1,3,7,2022-08-04,634344.0,Learner
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,630876.0,Learner
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,628848.0,Learner

In [93]:
df["salary_rank"]=df["salary"].rank(ascending=False)

In [94]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Learner,27.0
1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner,14.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Learner,29.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Learner,28.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,Marketing,Chennai,22.000000,55740.0,0,5,22,2020-04-22,668880.0,Learner,86.0
96,172,Neha Desai,Hr,Chennai,22.000000,52250.0,0,5,7,2020-11-14,627000.0,Learner,94.0
97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06,755634.0,Experienced candidate,50.5
98,193,Priya Nayak,Hr,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07,681852.0,Learner,80.0
99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25,833988.0,Experienced candidate,31.0

In [95]:
df.sort_values(by="salary_rank")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
75,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,6,17,2021-02-26,1060392.0,Experienced candidate,1.5
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,1.5
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,3.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,4.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,608796.0,Learner,96.0
67,169,Swati Chatterjee,Hr,Pune,33.0,49801.0,3,6,11,2021-08-20,597612.0,Learner,97.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,596316.0,Learner,98.0
36,167,Meera Malhotra,Hr,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,585864.0,Learner,99.0
26,141,Manish Kulkarni,Hr,Chennai,27.0,45835.0,3,8,13,2022-07-21,550020.0,Learner,100.0

In [96]:
df.duplicated().sum()

0

In [97]:
df.duplicated(subset=["employee_id"]).sum()

4

In [99]:
df.drop_duplicates(subset=["employee_id"], keep="first",inplace=True)

In [100]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Learner,27.0
1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner,14.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Learner,29.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Learner,28.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,Marketing,Chennai,22.000000,55740.0,0,5,22,2020-04-22,668880.0,Learner,86.0
96,172,Neha Desai,Hr,Chennai,22.000000,52250.0,0,5,7,2020-11-14,627000.0,Learner,94.0
97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06,755634.0,Experienced candidate,50.5
98,193,Priya Nayak,Hr,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07,681852.0,Learner,80.0
99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25,833988.0,Experienced candidate,31.0

In [101]:
df.nlargest(5, "salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,1.5
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,3.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,4.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,5.0
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Learner,6.0

In [103]:
df["age"]=df["age"].astype(int)

In [105]:
df.groupby("city")["age"].mean()

city
Bangalore    33.500000
Chennai      29.400000
Delhi        33.000000
Hyderabad    30.892857
Kolkata      28.000000
Mumbai       27.666667
Pune         31.642857
Name: age, dtype: float64

In [106]:
df.groupby(["city","department"])["salary"].mean()

city       department
Bangalore  Data Science    72862.000000
           Engineering     79164.500000
           Finance         67015.750000
           Hr              67048.000000
           Marketing       62080.666667
Chennai    Engineering     73129.000000
           Finance         71889.000000
           Hr              49042.500000
           Marketing       59354.750000
           Sales           57858.000000
Delhi      Data Science    76267.000000
           Engineering     71663.750000
           Finance         66422.000000
           Hr              58917.600000
           Marketing       62910.000000
           Sales           66095.000000
Hyderabad  Data Science    81502.333333
           Engineering     76730.500000
           Finance         69947.071429
           Hr              58083.285714
           Marketing       55663.400000
           Sales           57669.125000
Kolkata    Data Science    72303.000000
           Engineering     79740.500000
           Finance         58857.666667
           Hr              55542.000000
           Marketing       59186.000000
           Sales           60015.000000
Mumbai     Data Science    78465.000000
           Engineering     70013.750000
           Finance         64112.000000
           Hr              88366.000000
           Marketing       61513.500000
           Sales           52862.000000
Pune       Data Science    75498.000000
           Engineering     70502.500000
           Finance         61267.000000
           Hr              59159.000000
           Marketing       58481.000000
Name: salary, dtype: float64

In [107]:
df.groupby("department").agg({
    "salary": ["mean", "max"],
    "performance_score": "mean",
    "employee_id": "count"
})

                    salary          performance_score employee_id
                      mean      max              mean       count
department
Data Science  76450.800000  88216.0          5.700000          10
Engineering   74038.205882  84870.0          5.705882          17
Finance       66187.705882  80597.0          5.294118          17
Hr            59524.875000  88366.0          5.708333          24
Marketing     59382.000000  69499.0          5.894737          19
Sales         59289.055556  68490.0          6.555556           9

In [108]:
department_summary = df.groupby("department").agg(
    average_salary=("salary", "mean"),
    highest_salary=("salary", "max"),
    employee_count=("employee_id", "count")
)

In [110]:
department_summary

              average_salary  highest_salary  employee_count
department
Data Science    76450.800000         88216.0              10
Engineering     74038.205882         84870.0              17
Finance         66187.705882         80597.0              17
Hr              59524.875000         88366.0              24
Marketing       59382.000000         69499.0              19
Sales           59289.055556         68490.0               9

In [2]:
import pandas as pd
dummy=pd.Series([10,20,30,40])
dummy

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
data={"Name":["aman","riya","karan","sneha","nilesh"],
      "Age":[18,19,18,20,19],
      "Marks":[85,92,76,88,95]}
dummy_df=pd.DataFrame(data)
dummy_df.describe()

            Age      Marks
count   5.00000   5.000000
mean   18.80000  87.200000
std     0.83666   7.328028
min    18.00000  76.000000
25%    18.00000  85.000000
50%    19.00000  88.000000
75%    19.00000  92.000000
max    20.00000  95.000000

In [8]:
dummy_df["Name"]

0      aman
1      riya
2     karan
3     sneha
4    nilesh
Name: Name, dtype: object

In [10]:
dummy_df[dummy_df["Marks"]>80]

     Name  Age  Marks
0    aman   18     85
1    riya   19     92
3   sneha   20     88
4  nilesh   19     95

In [12]:
dummy_df.iloc[:3]

    Name  Age  Marks
0   aman   18     85
1   riya   19     92
2  karan   18     76

In [ ]:
dummy_df["Marks"].mean()

87.2

In [17]:
dummy_df["Marks"].max()
dummy_df.loc[dummy_df["Marks"].idxmax()]

Name         nilesh
Age              19
Marks            95
pass/fail      pass
Name: 4, dtype: object

In [16]:
dummy_df["pass/fail"]=dummy_df["Marks"].apply(lambda x: "pass" if x>=40 else "fail")
dummy_df

     Name  Age  Marks pass/fail
0    aman   18     85      pass
1    riya   19     92      pass
2   karan   18     76      pass
3   sneha   20     88      pass
4  nilesh   19     95      pass

In [19]:
(dummy_df["Marks"]>90).sum()

2

In [20]:
students_df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Sneha", "Nilesh"],
    "Marks": [85, 92, None, 88, 95]   # Notice the NaN
})

students_df["Marks"].fillna(students_df["Marks"].mean(), inplace=True)
print(students_df)

     Name  Marks
0    Aman   85.0
1    Riya   92.0
2   Karan   90.0
3   Sneha   88.0
4  Nilesh   95.0

C:\Users\kashy\AppData\Local\Temp\ipykernel_32972\2072032255.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students_df["Marks"].fillna(students_df["Marks"].mean(), inplace=True)